"""
    Ternary Platform API

    Ternary Platform API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from ternary.api_client import ApiClient, Endpoint as _Endpoint
from ternary.model_utils import (  # noqa: F401
    check_allowed_values,
    check_validations,
    date,
    datetime,
    file_type,
    none_type,
    validate_and_convert_types
)
from ternary.model.api_http_error import ApiHttpError
from ternary.model.model_custom_label import ModelCustomLabel
from ternary.model.model_key_values import ModelKeyValues


class CustomLabelsApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

        def __tenants_tenant_id_clouds_cloud_id_custom_labels_custom_label_id_delete(
            self,
            tenant_id,
            cloud_id,
            **kwargs
        ):
            """Delete Custom Label  # noqa: E501

            Delete an existing Custom Label within a specific Tenant and Cloud by its ID  # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.tenants_tenant_id_clouds_cloud_id_custom_labels_custom_label_id_delete(tenant_id, cloud_id, async_req=True)
            >>> result = thread.get()

            Args:
                tenant_id (str): Tenant ID
                cloud_id (str): Cloud ID

            Keyword Args:
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                None
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['tenant_id'] = \
                tenant_id
            kwargs['cloud_id'] = \
                cloud_id
            return self.call_with_http_info(**kwargs)

        self.tenants_tenant_id_clouds_cloud_id_custom_labels_custom_label_id_delete = _Endpoint(
            settings={
                'response_type': None,
                'auth': [],
                'endpoint_path': '/tenants/{tenant_id}/clouds/{cloud_id}/custom_labels/{custom_label_id}',
                'operation_id': 'tenants_tenant_id_clouds_cloud_id_custom_labels_custom_label_id_delete',
                'http_method': 'DELETE',
                'servers': None,
            },
            params_map={
                'all': [
                    'tenant_id',
                    'cloud_id',
                ],
                'required': [
                    'tenant_id',
                    'cloud_id',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'tenant_id':
                        (str,),
                    'cloud_id':
                        (str,),
                },
                'attribute_map': {
                    'tenant_id': 'tenant_id',
                    'cloud_id': 'cloud_id',
                },
                'location_map': {
                    'tenant_id': 'path',
                    'cloud_id': 'path',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    '*/*'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__tenants_tenant_id_clouds_cloud_id_custom_labels_custom_label_id_delete
        )

        def __tenants_tenant_id_clouds_cloud_id_custom_labels_custom_label_id_get(
            self,
            tenant_id,
            cloud_id,
            custom_label_id,
            **kwargs
        ):
            """Get Custom Label  # noqa: E501

            Get a Custom Label in a Tenant's Cloud by its ID.  # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.tenants_tenant_id_clouds_cloud_id_custom_labels_custom_label_id_get(tenant_id, cloud_id, custom_label_id, async_req=True)
            >>> result = thread.get()

            Args:
                tenant_id (str): Tenant ID
                cloud_id (str): Cloud ID
                custom_label_id (str): Custom Label ID

            Keyword Args:
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                ModelCustomLabel
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['tenant_id'] = \
                tenant_id
            kwargs['cloud_id'] = \
                cloud_id
            kwargs['custom_label_id'] = \
                custom_label_id
            return self.call_with_http_info(**kwargs)

        self.tenants_tenant_id_clouds_cloud_id_custom_labels_custom_label_id_get = _Endpoint(
            settings={
                'response_type': (ModelCustomLabel,),
                'auth': [],
                'endpoint_path': '/tenants/{tenant_id}/clouds/{cloud_id}/custom_labels/{custom_label_id}',
                'operation_id': 'tenants_tenant_id_clouds_cloud_id_custom_labels_custom_label_id_get',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'tenant_id',
                    'cloud_id',
                    'custom_label_id',
                ],
                'required': [
                    'tenant_id',
                    'cloud_id',
                    'custom_label_id',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'tenant_id':
                        (str,),
                    'cloud_id':
                        (str,),
                    'custom_label_id':
                        (str,),
                },
                'attribute_map': {
                    'tenant_id': 'tenant_id',
                    'cloud_id': 'cloud_id',
                    'custom_label_id': 'custom_label_id',
                },
                'location_map': {
                    'tenant_id': 'path',
                    'cloud_id': 'path',
                    'custom_label_id': 'path',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__tenants_tenant_id_clouds_cloud_id_custom_labels_custom_label_id_get
        )

        def __tenants_tenant_id_clouds_cloud_id_custom_labels_custom_label_id_put(
            self,
            tenant_id,
            cloud_id,
            custom_label_id,
            custom_label,
            **kwargs
        ):
            """Update Custom Label  # noqa: E501

            Update an existing Custom Label  # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.tenants_tenant_id_clouds_cloud_id_custom_labels_custom_label_id_put(tenant_id, cloud_id, custom_label_id, custom_label, async_req=True)
            >>> result = thread.get()

            Args:
                tenant_id (str): Tenant ID
                cloud_id (str): Cloud ID
                custom_label_id (str): Custom Label ID
                custom_label (ModelCustomLabel): Custom Label JSON

            Keyword Args:
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                ModelCustomLabel
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['tenant_id'] = \
                tenant_id
            kwargs['cloud_id'] = \
                cloud_id
            kwargs['custom_label_id'] = \
                custom_label_id
            kwargs['custom_label'] = \
                custom_label
            return self.call_with_http_info(**kwargs)

        self.tenants_tenant_id_clouds_cloud_id_custom_labels_custom_label_id_put = _Endpoint(
            settings={
                'response_type': (ModelCustomLabel,),
                'auth': [],
                'endpoint_path': '/tenants/{tenant_id}/clouds/{cloud_id}/custom_labels/{custom_label_id}',
                'operation_id': 'tenants_tenant_id_clouds_cloud_id_custom_labels_custom_label_id_put',
                'http_method': 'PUT',
                'servers': None,
            },
            params_map={
                'all': [
                    'tenant_id',
                    'cloud_id',
                    'custom_label_id',
                    'custom_label',
                ],
                'required': [
                    'tenant_id',
                    'cloud_id',
                    'custom_label_id',
                    'custom_label',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'tenant_id':
                        (str,),
                    'cloud_id':
                        (str,),
                    'custom_label_id':
                        (str,),
                    'custom_label':
                        (ModelCustomLabel,),
                },
                'attribute_map': {
                    'tenant_id': 'tenant_id',
                    'cloud_id': 'cloud_id',
                    'custom_label_id': 'custom_label_id',
                },
                'location_map': {
                    'tenant_id': 'path',
                    'cloud_id': 'path',
                    'custom_label_id': 'path',
                    'custom_label': 'body',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client,
            callable=__tenants_tenant_id_clouds_cloud_id_custom_labels_custom_label_id_put
        )

        def __tenants_tenant_id_clouds_cloud_id_custom_labels_get(
            self,
            tenant_id,
            cloud_id,
            **kwargs
        ):
            """List Custom Labels  # noqa: E501

            Get all Custom labels in the Tenant's Cloud.  # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.tenants_tenant_id_clouds_cloud_id_custom_labels_get(tenant_id, cloud_id, async_req=True)
            >>> result = thread.get()

            Args:
                tenant_id (str): Tenant ID
                cloud_id (str): Cloud ID

            Keyword Args:
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                [ModelCustomLabel]
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['tenant_id'] = \
                tenant_id
            kwargs['cloud_id'] = \
                cloud_id
            return self.call_with_http_info(**kwargs)

        self.tenants_tenant_id_clouds_cloud_id_custom_labels_get = _Endpoint(
            settings={
                'response_type': ([ModelCustomLabel],),
                'auth': [],
                'endpoint_path': '/tenants/{tenant_id}/clouds/{cloud_id}/custom_labels',
                'operation_id': 'tenants_tenant_id_clouds_cloud_id_custom_labels_get',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'tenant_id',
                    'cloud_id',
                ],
                'required': [
                    'tenant_id',
                    'cloud_id',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'tenant_id':
                        (str,),
                    'cloud_id':
                        (str,),
                },
                'attribute_map': {
                    'tenant_id': 'tenant_id',
                    'cloud_id': 'cloud_id',
                },
                'location_map': {
                    'tenant_id': 'path',
                    'cloud_id': 'path',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__tenants_tenant_id_clouds_cloud_id_custom_labels_get
        )

        def __tenants_tenant_id_clouds_cloud_id_custom_labels_post(
            self,
            tenant_id,
            cloud_id,
            custom_labels,
            **kwargs
        ):
            """Create Custom Labels  # noqa: E501

            Create new Custom Labels in the Tenant's Cloud.  # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.tenants_tenant_id_clouds_cloud_id_custom_labels_post(tenant_id, cloud_id, custom_labels, async_req=True)
            >>> result = thread.get()

            Args:
                tenant_id (str): Tenant ID
                cloud_id (str): Cloud ID
                custom_labels ([ModelCustomLabel]): Custom Labels JSON

            Keyword Args:
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                [ModelCustomLabel]
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['tenant_id'] = \
                tenant_id
            kwargs['cloud_id'] = \
                cloud_id
            kwargs['custom_labels'] = \
                custom_labels
            return self.call_with_http_info(**kwargs)

        self.tenants_tenant_id_clouds_cloud_id_custom_labels_post = _Endpoint(
            settings={
                'response_type': ([ModelCustomLabel],),
                'auth': [],
                'endpoint_path': '/tenants/{tenant_id}/clouds/{cloud_id}/custom_labels',
                'operation_id': 'tenants_tenant_id_clouds_cloud_id_custom_labels_post',
                'http_method': 'POST',
                'servers': None,
            },
            params_map={
                'all': [
                    'tenant_id',
                    'cloud_id',
                    'custom_labels',
                ],
                'required': [
                    'tenant_id',
                    'cloud_id',
                    'custom_labels',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'tenant_id':
                        (str,),
                    'cloud_id':
                        (str,),
                    'custom_labels':
                        ([ModelCustomLabel],),
                },
                'attribute_map': {
                    'tenant_id': 'tenant_id',
                    'cloud_id': 'cloud_id',
                },
                'location_map': {
                    'tenant_id': 'path',
                    'cloud_id': 'path',
                    'custom_labels': 'body',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client,
            callable=__tenants_tenant_id_clouds_cloud_id_custom_labels_post
        )

        def __v1_tenants_tenant_id_clouds_cloud_id_all_labels_get(
            self,
            tenant_id,
            cloud_id,
            **kwargs
        ):
            """List All Labels in Billing Export  # noqa: E501

            Materialize a list of all of the keys and corresponding values that currently exist in the billing export including Custom Labels  # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.v1_tenants_tenant_id_clouds_cloud_id_all_labels_get(tenant_id, cloud_id, async_req=True)
            >>> result = thread.get()

            Args:
                tenant_id (str): Tenant ID
                cloud_id (str): Cloud ID

            Keyword Args:
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                [ModelKeyValues]
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['tenant_id'] = \
                tenant_id
            kwargs['cloud_id'] = \
                cloud_id
            return self.call_with_http_info(**kwargs)

        self.v1_tenants_tenant_id_clouds_cloud_id_all_labels_get = _Endpoint(
            settings={
                'response_type': ([ModelKeyValues],),
                'auth': [],
                'endpoint_path': '/v1/tenants/{tenant_id}/clouds/{cloud_id}/all_labels',
                'operation_id': 'v1_tenants_tenant_id_clouds_cloud_id_all_labels_get',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'tenant_id',
                    'cloud_id',
                ],
                'required': [
                    'tenant_id',
                    'cloud_id',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'tenant_id':
                        (str,),
                    'cloud_id':
                        (str,),
                },
                'attribute_map': {
                    'tenant_id': 'tenant_id',
                    'cloud_id': 'cloud_id',
                },
                'location_map': {
                    'tenant_id': 'path',
                    'cloud_id': 'path',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__v1_tenants_tenant_id_clouds_cloud_id_all_labels_get
        )
