"""
    Ternary Platform API

    Ternary Platform API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import ternary
from ternary.api.tenants_api import TenantsApi  # noqa: E501


class TestTenantsApi(unittest.TestCase):
    """TenantsApi unit test stubs"""

    def setUp(self):
        self.api = TenantsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_tenants_get(self):
        """Test case for tenants_get

        List Tenants  # noqa: E501
        """
        pass

    def test_tenants_tenant_id_get(self):
        """Test case for tenants_tenant_id_get

        Get Tenant  # noqa: E501
        """
        pass

    def test_tenants_tenant_id_put(self):
        """Test case for tenants_tenant_id_put

        Update Tenant  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
