"""
    Ternary Platform API

    Ternary Platform API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ternary
from ternary.model.cube_cube_access_token import CubeCubeAccessToken


class TestCubeCubeAccessToken(unittest.TestCase):
    """CubeCubeAccessToken unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCubeCubeAccessToken(self):
        """Test CubeCubeAccessToken"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CubeCubeAccessToken()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
