"""
    Ternary Platform API

    Ternary Platform API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ternary
from ternary.model.model_notification_target import ModelNotificationTarget


class TestModelNotificationTarget(unittest.TestCase):
    """ModelNotificationTarget unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelNotificationTarget(self):
        """Test ModelNotificationTarget"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ModelNotificationTarget()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
