"""
    Ternary Platform API

    Ternary Platform API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import ternary
from ternary.api.integration_api import IntegrationApi  # noqa: E501


class TestIntegrationApi(unittest.TestCase):
    """IntegrationApi unit test stubs"""

    def setUp(self):
        self.api = IntegrationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_tenants_tenant_id_integrations_get(self):
        """Test case for tenants_tenant_id_integrations_get

        List Integrations  # noqa: E501
        """
        pass

    def test_tenants_tenant_id_integrations_integration_id_delete(self):
        """Test case for tenants_tenant_id_integrations_integration_id_delete

        Delete Integration  # noqa: E501
        """
        pass

    def test_tenants_tenant_id_integrations_integration_id_put(self):
        """Test case for tenants_tenant_id_integrations_integration_id_put

        Update Integration  # noqa: E501
        """
        pass

    def test_tenants_tenant_id_integrations_integration_id_slack_channels_get(self):
        """Test case for tenants_tenant_id_integrations_integration_id_slack_channels_get

        List Channels for Slack Integration  # noqa: E501
        """
        pass

    def test_tenants_tenant_id_integrations_slack_post(self):
        """Test case for tenants_tenant_id_integrations_slack_post

        Create Slack Integration  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
