"""
    Ternary Platform API

    Ternary Platform API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ternary
from ternary.model.model_budget_specified_amount import ModelBudgetSpecifiedAmount


class TestModelBudgetSpecifiedAmount(unittest.TestCase):
    """ModelBudgetSpecifiedAmount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelBudgetSpecifiedAmount(self):
        """Test ModelBudgetSpecifiedAmount"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ModelBudgetSpecifiedAmount()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
