"""
    Ternary Platform API

    Ternary Platform API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import ternary
from ternary.api.recommendation_types_api import RecommendationTypesApi  # noqa: E501


class TestRecommendationTypesApi(unittest.TestCase):
    """RecommendationTypesApi unit test stubs"""

    def setUp(self):
        self.api = RecommendationTypesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_recommendation_types_get(self):
        """Test case for recommendation_types_get

        List Recommendation Types  # noqa: E501
        """
        pass

    def test_recommendation_types_id_get(self):
        """Test case for recommendation_types_id_get

        Get Recommendation Type  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
