"""
    Ternary Platform API

    Ternary Platform API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import ternary
from ternary.api.clouds_api import CloudsApi  # noqa: E501


class TestCloudsApi(unittest.TestCase):
    """CloudsApi unit test stubs"""

    def setUp(self):
        self.api = CloudsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_tenants_tenant_id_clouds_get(self):
        """Test case for tenants_tenant_id_clouds_get

        List Clouds  # noqa: E501
        """
        pass

    def test_tenants_tenant_id_clouds_id_delete(self):
        """Test case for tenants_tenant_id_clouds_id_delete

        Delete Cloud  # noqa: E501
        """
        pass

    def test_tenants_tenant_id_clouds_id_get(self):
        """Test case for tenants_tenant_id_clouds_id_get

        Get Cloud  # noqa: E501
        """
        pass

    def test_tenants_tenant_id_clouds_id_put(self):
        """Test case for tenants_tenant_id_clouds_id_put

        Update Cloud  # noqa: E501
        """
        pass

    def test_tenants_tenant_id_clouds_id_validate_post(self):
        """Test case for tenants_tenant_id_clouds_id_validate_post

        Validate Cloud  # noqa: E501
        """
        pass

    def test_tenants_tenant_id_clouds_post(self):
        """Test case for tenants_tenant_id_clouds_post

        Create Cloud  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
