"""
    Ternary Platform API

    Ternary Platform API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ternary
from ternary.model.model_delta_driver import ModelDeltaDriver
from ternary.model.model_recommendation import ModelRecommendation
globals()['ModelDeltaDriver'] = ModelDeltaDriver
globals()['ModelRecommendation'] = ModelRecommendation
from ternary.model.model_daily_report_event import ModelDailyReportEvent


class TestModelDailyReportEvent(unittest.TestCase):
    """ModelDailyReportEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelDailyReportEvent(self):
        """Test ModelDailyReportEvent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ModelDailyReportEvent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
