"""
    Ternary Platform API

    Ternary Platform API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import ternary
from ternary.api.notification_api import NotificationApi  # noqa: E501


class TestNotificationApi(unittest.TestCase):
    """NotificationApi unit test stubs"""

    def setUp(self):
        self.api = NotificationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_tenants_tenant_id_notifications_get(self):
        """Test case for tenants_tenant_id_notifications_get

        List User Notifications  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
