"""
    Ternary Platform API

    Ternary Platform API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ternary
from ternary.model.model_user_notifications import ModelUserNotifications
globals()['ModelUserNotifications'] = ModelUserNotifications
from ternary.model.model_user import ModelUser


class TestModelUser(unittest.TestCase):
    """ModelUser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelUser(self):
        """Test ModelUser"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ModelUser()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
