"""
    Ternary Platform API

    Ternary Platform API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import ternary
from ternary.api.recommendations_api import RecommendationsApi  # noqa: E501


class TestRecommendationsApi(unittest.TestCase):
    """RecommendationsApi unit test stubs"""

    def setUp(self):
        self.api = RecommendationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_tenants_tenant_id_recommendations_get(self):
        """Test case for tenants_tenant_id_recommendations_get

        List Recommendations  # noqa: E501
        """
        pass

    def test_tenants_tenant_id_recommendations_id_comments_get(self):
        """Test case for tenants_tenant_id_recommendations_id_comments_get

        Get Recommendation Comments  # noqa: E501
        """
        pass

    def test_tenants_tenant_id_recommendations_id_comments_post(self):
        """Test case for tenants_tenant_id_recommendations_id_comments_post

        Create Recommendation Comment  # noqa: E501
        """
        pass

    def test_tenants_tenant_id_recommendations_id_delete(self):
        """Test case for tenants_tenant_id_recommendations_id_delete

        Delete Recommendation  # noqa: E501
        """
        pass

    def test_tenants_tenant_id_recommendations_id_get(self):
        """Test case for tenants_tenant_id_recommendations_id_get

        Get Recommendation  # noqa: E501
        """
        pass

    def test_tenants_tenant_id_recommendations_id_put(self):
        """Test case for tenants_tenant_id_recommendations_id_put

        Update Recommendation  # noqa: E501
        """
        pass

    def test_tenants_tenant_id_recommendations_post(self):
        """Test case for tenants_tenant_id_recommendations_post

        Create Recommendation  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
