"""
    Ternary Platform API

    Ternary Platform API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ternary
from ternary.model.model_recommendation_detail import ModelRecommendationDetail


class TestModelRecommendationDetail(unittest.TestCase):
    """ModelRecommendationDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelRecommendationDetail(self):
        """Test ModelRecommendationDetail"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ModelRecommendationDetail()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
