"""
    Ternary Platform API

    Ternary Platform API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import ternary
from ternary.api.custom_labels_api import CustomLabelsApi  # noqa: E501


class TestCustomLabelsApi(unittest.TestCase):
    """CustomLabelsApi unit test stubs"""

    def setUp(self):
        self.api = CustomLabelsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_tenants_tenant_id_clouds_cloud_id_custom_labels_custom_label_id_delete(self):
        """Test case for tenants_tenant_id_clouds_cloud_id_custom_labels_custom_label_id_delete

        Delete Custom Label  # noqa: E501
        """
        pass

    def test_tenants_tenant_id_clouds_cloud_id_custom_labels_custom_label_id_get(self):
        """Test case for tenants_tenant_id_clouds_cloud_id_custom_labels_custom_label_id_get

        Get Custom Label  # noqa: E501
        """
        pass

    def test_tenants_tenant_id_clouds_cloud_id_custom_labels_custom_label_id_put(self):
        """Test case for tenants_tenant_id_clouds_cloud_id_custom_labels_custom_label_id_put

        Update Custom Label  # noqa: E501
        """
        pass

    def test_tenants_tenant_id_clouds_cloud_id_custom_labels_get(self):
        """Test case for tenants_tenant_id_clouds_cloud_id_custom_labels_get

        List Custom Labels  # noqa: E501
        """
        pass

    def test_tenants_tenant_id_clouds_cloud_id_custom_labels_post(self):
        """Test case for tenants_tenant_id_clouds_cloud_id_custom_labels_post

        Create Custom Labels  # noqa: E501
        """
        pass

    def test_v1_tenants_tenant_id_clouds_cloud_id_all_labels_get(self):
        """Test case for v1_tenants_tenant_id_clouds_cloud_id_all_labels_get

        List All Labels in Billing Export  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
