"""
    Ternary Platform API

    Ternary Platform API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ternary
from ternary.model.model_big_query_monitoring import ModelBigQueryMonitoring


class TestModelBigQueryMonitoring(unittest.TestCase):
    """ModelBigQueryMonitoring unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelBigQueryMonitoring(self):
        """Test ModelBigQueryMonitoring"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ModelBigQueryMonitoring()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
