"""
    Ternary Platform API

    Ternary Platform API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import ternary
from ternary.api.grants_api import GrantsApi  # noqa: E501


class TestGrantsApi(unittest.TestCase):
    """GrantsApi unit test stubs"""

    def setUp(self):
        self.api = GrantsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_tenants_tenant_id_grants_email_delete(self):
        """Test case for tenants_tenant_id_grants_email_delete

        Delete Grant  # noqa: E501
        """
        pass

    def test_tenants_tenant_id_grants_get(self):
        """Test case for tenants_tenant_id_grants_get

        List Grants  # noqa: E501
        """
        pass

    def test_tenants_tenant_id_grants_post(self):
        """Test case for tenants_tenant_id_grants_post

        Create/Update Grant  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
