"""
    Ternary Platform API

    Ternary Platform API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ternary
from ternary.model.model_cloud_capability import ModelCloudCapability
globals()['ModelCloudCapability'] = ModelCloudCapability
from ternary.model.model_cloud_status import ModelCloudStatus


class TestModelCloudStatus(unittest.TestCase):
    """ModelCloudStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelCloudStatus(self):
        """Test ModelCloudStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ModelCloudStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
