"""
    Ternary Platform API

    Ternary Platform API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ternary
from ternary.model.api_http_error import ApiHttpError


class TestApiHttpError(unittest.TestCase):
    """ApiHttpError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiHttpError(self):
        """Test ApiHttpError"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApiHttpError()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
