"""
    Ternary Platform API

    Ternary Platform API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ternary
from ternary.model.model_budget import ModelBudget
from ternary.model.model_budget_threshold import ModelBudgetThreshold
globals()['ModelBudget'] = ModelBudget
globals()['ModelBudgetThreshold'] = ModelBudgetThreshold
from ternary.model.model_budget_event import ModelBudgetEvent


class TestModelBudgetEvent(unittest.TestCase):
    """ModelBudgetEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelBudgetEvent(self):
        """Test ModelBudgetEvent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ModelBudgetEvent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
