"""
    Ternary Platform API

    Ternary Platform API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ternary
from ternary.model.model_budget_event import ModelBudgetEvent
from ternary.model.model_daily_report_event import ModelDailyReportEvent
from ternary.model.model_recommendation_event import ModelRecommendationEvent
globals()['ModelBudgetEvent'] = ModelBudgetEvent
globals()['ModelDailyReportEvent'] = ModelDailyReportEvent
globals()['ModelRecommendationEvent'] = ModelRecommendationEvent
from ternary.model.model_notification_content import ModelNotificationContent


class TestModelNotificationContent(unittest.TestCase):
    """ModelNotificationContent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelNotificationContent(self):
        """Test ModelNotificationContent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ModelNotificationContent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
