"""
    Ternary Platform API

    Ternary Platform API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import ternary
from ternary.api.budgets_api import BudgetsApi  # noqa: E501


class TestBudgetsApi(unittest.TestCase):
    """BudgetsApi unit test stubs"""

    def setUp(self):
        self.api = BudgetsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v1_tenants_tenant_id_budgets_budget_id_delete(self):
        """Test case for v1_tenants_tenant_id_budgets_budget_id_delete

        Delete Budget  # noqa: E501
        """
        pass

    def test_v1_tenants_tenant_id_budgets_budget_id_get(self):
        """Test case for v1_tenants_tenant_id_budgets_budget_id_get

        Get Budget  # noqa: E501
        """
        pass

    def test_v1_tenants_tenant_id_budgets_budget_id_put(self):
        """Test case for v1_tenants_tenant_id_budgets_budget_id_put

        Update Budget  # noqa: E501
        """
        pass

    def test_v1_tenants_tenant_id_budgets_get(self):
        """Test case for v1_tenants_tenant_id_budgets_get

        List Budgets  # noqa: E501
        """
        pass

    def test_v1_tenants_tenant_id_budgets_post(self):
        """Test case for v1_tenants_tenant_id_budgets_post

        Create Budget  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
