"""
    Ternary Platform API

    Ternary Platform API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ternary
from ternary.model.model_notification_profile import ModelNotificationProfile


class TestModelNotificationProfile(unittest.TestCase):
    """ModelNotificationProfile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelNotificationProfile(self):
        """Test ModelNotificationProfile"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ModelNotificationProfile()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
