"""
    Ternary Platform API

    Ternary Platform API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ternary
from ternary.model.model_project_list_response import ModelProjectListResponse


class TestModelProjectListResponse(unittest.TestCase):
    """ModelProjectListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelProjectListResponse(self):
        """Test ModelProjectListResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ModelProjectListResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
