"""
    Ternary Platform API

    Ternary Platform API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ternary
from ternary.model.model_budget_threshold import ModelBudgetThreshold
globals()['ModelBudgetThreshold'] = ModelBudgetThreshold
from ternary.model.model_budget_status import ModelBudgetStatus


class TestModelBudgetStatus(unittest.TestCase):
    """ModelBudgetStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelBudgetStatus(self):
        """Test ModelBudgetStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ModelBudgetStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
