"""
    Ternary Platform API

    Ternary Platform API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ternary
from ternary.model.model_notification_profile import ModelNotificationProfile
globals()['ModelNotificationProfile'] = ModelNotificationProfile
from ternary.model.model_user_notifications import ModelUserNotifications


class TestModelUserNotifications(unittest.TestCase):
    """ModelUserNotifications unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelUserNotifications(self):
        """Test ModelUserNotifications"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ModelUserNotifications()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
