"""
    Ternary Platform API

    Ternary Platform API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ternary
from ternary.model.model_profile import ModelProfile
from ternary.model.model_user_notifications import ModelUserNotifications
globals()['ModelProfile'] = ModelProfile
globals()['ModelUserNotifications'] = ModelUserNotifications
from ternary.model.v1_user_with_profile import V1UserWithProfile


class TestV1UserWithProfile(unittest.TestCase):
    """V1UserWithProfile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1UserWithProfile(self):
        """Test V1UserWithProfile"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1UserWithProfile()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
