"""
    Ternary Platform API

    Ternary Platform API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ternary
from ternary.model.model_notification_content import ModelNotificationContent
from ternary.model.model_notification_target import ModelNotificationTarget
globals()['ModelNotificationContent'] = ModelNotificationContent
globals()['ModelNotificationTarget'] = ModelNotificationTarget
from ternary.model.model_notification import ModelNotification


class TestModelNotification(unittest.TestCase):
    """ModelNotification unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelNotification(self):
        """Test ModelNotification"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ModelNotification()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
