"""
    Ternary Platform API

    Ternary Platform API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ternary
from ternary.model.model_budget_amount import ModelBudgetAmount
from ternary.model.model_budget_scope import ModelBudgetScope
from ternary.model.model_budget_status import ModelBudgetStatus
from ternary.model.model_budget_threshold import ModelBudgetThreshold
globals()['ModelBudgetAmount'] = ModelBudgetAmount
globals()['ModelBudgetScope'] = ModelBudgetScope
globals()['ModelBudgetStatus'] = ModelBudgetStatus
globals()['ModelBudgetThreshold'] = ModelBudgetThreshold
from ternary.model.model_budget import ModelBudget


class TestModelBudget(unittest.TestCase):
    """ModelBudget unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelBudget(self):
        """Test ModelBudget"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ModelBudget()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
