"""
    Ternary Platform API

    Ternary Platform API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ternary
from ternary.model.model_tenant_anomaly_profile import ModelTenantAnomalyProfile


class TestModelTenantAnomalyProfile(unittest.TestCase):
    """ModelTenantAnomalyProfile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelTenantAnomalyProfile(self):
        """Test ModelTenantAnomalyProfile"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ModelTenantAnomalyProfile()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
