"""
    Ternary Platform API

    Ternary Platform API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ternary
from ternary.model.model_recommendation_type import ModelRecommendationType


class TestModelRecommendationType(unittest.TestCase):
    """ModelRecommendationType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelRecommendationType(self):
        """Test ModelRecommendationType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ModelRecommendationType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
