"""
    Ternary Platform API

    Ternary Platform API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ternary
from ternary.model.model_big_query_monitoring import ModelBigQueryMonitoring
from ternary.model.model_big_query_table import ModelBigQueryTable
globals()['ModelBigQueryMonitoring'] = ModelBigQueryMonitoring
globals()['ModelBigQueryTable'] = ModelBigQueryTable
from ternary.model.model_google_cloud import ModelGoogleCloud


class TestModelGoogleCloud(unittest.TestCase):
    """ModelGoogleCloud unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelGoogleCloud(self):
        """Test ModelGoogleCloud"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ModelGoogleCloud()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
