"""
    Ternary Platform API

    Ternary Platform API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ternary
from ternary.model.model_big_query_table import ModelBigQueryTable


class TestModelBigQueryTable(unittest.TestCase):
    """ModelBigQueryTable unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelBigQueryTable(self):
        """Test ModelBigQueryTable"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ModelBigQueryTable()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
