"""
    Ternary Platform API

    Ternary Platform API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ternary
from ternary.model.model_custom_label_matcher import ModelCustomLabelMatcher
from ternary.model.model_custom_label_output import ModelCustomLabelOutput
globals()['ModelCustomLabelMatcher'] = ModelCustomLabelMatcher
globals()['ModelCustomLabelOutput'] = ModelCustomLabelOutput
from ternary.model.model_custom_label import ModelCustomLabel


class TestModelCustomLabel(unittest.TestCase):
    """ModelCustomLabel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelCustomLabel(self):
        """Test ModelCustomLabel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ModelCustomLabel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
