"""
    Ternary Platform API

    Ternary Platform API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import ternary
from ternary.api.query_api import QueryApi  # noqa: E501


class TestQueryApi(unittest.TestCase):
    """QueryApi unit test stubs"""

    def setUp(self):
        self.api = QueryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_tenants_tenant_id_clouds_cloud_id_projects_get(self):
        """Test case for tenants_tenant_id_clouds_cloud_id_projects_get

        List Projects for Tenant's Cloud  # noqa: E501
        """
        pass

    def test_tenants_tenant_id_cubejs_token_post(self):
        """Test case for tenants_tenant_id_cubejs_token_post

        Generate Cube Access Token  # noqa: E501
        """
        pass

    def test_zendesk_token_post(self):
        """Test case for zendesk_token_post

        Generate Zendesk Access Token  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
