"""
    Ternary Platform API

    Ternary Platform API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ternary
from ternary.model.model_recommendation import ModelRecommendation
from ternary.model.model_recommendation_comment import ModelRecommendationComment
globals()['ModelRecommendation'] = ModelRecommendation
globals()['ModelRecommendationComment'] = ModelRecommendationComment
from ternary.model.model_recommendation_event import ModelRecommendationEvent


class TestModelRecommendationEvent(unittest.TestCase):
    """ModelRecommendationEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelRecommendationEvent(self):
        """Test ModelRecommendationEvent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ModelRecommendationEvent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
