"""
    Ternary Platform API

    Ternary Platform API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import ternary
from ternary.api.resources_api import ResourcesApi  # noqa: E501


class TestResourcesApi(unittest.TestCase):
    """ResourcesApi unit test stubs"""

    def setUp(self):
        self.api = ResourcesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_tenants_tenant_id_resources_get(self):
        """Test case for tenants_tenant_id_resources_get

        List Resources  # noqa: E501
        """
        pass

    def test_tenants_tenant_id_resources_id_delete(self):
        """Test case for tenants_tenant_id_resources_id_delete

        Delete Resource  # noqa: E501
        """
        pass

    def test_tenants_tenant_id_resources_id_get(self):
        """Test case for tenants_tenant_id_resources_id_get

        Get Resource  # noqa: E501
        """
        pass

    def test_tenants_tenant_id_resources_id_put(self):
        """Test case for tenants_tenant_id_resources_id_put

        Update Resource  # noqa: E501
        """
        pass

    def test_tenants_tenant_id_resources_post(self):
        """Test case for tenants_tenant_id_resources_post

        Create Resource  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
