"""
    Ternary Platform API

    Ternary Platform API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ternary
from ternary.model.model_budget_specified_amount import ModelBudgetSpecifiedAmount
globals()['ModelBudgetSpecifiedAmount'] = ModelBudgetSpecifiedAmount
from ternary.model.model_budget_amount import ModelBudgetAmount


class TestModelBudgetAmount(unittest.TestCase):
    """ModelBudgetAmount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelBudgetAmount(self):
        """Test ModelBudgetAmount"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ModelBudgetAmount()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
