"""
    Ternary Platform API

    Ternary Platform API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ternary
from ternary.model.model_cloud_status import ModelCloudStatus
from ternary.model.model_google_cloud import ModelGoogleCloud
globals()['ModelCloudStatus'] = ModelCloudStatus
globals()['ModelGoogleCloud'] = ModelGoogleCloud
from ternary.model.model_cloud import ModelCloud


class TestModelCloud(unittest.TestCase):
    """ModelCloud unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelCloud(self):
        """Test ModelCloud"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ModelCloud()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
