"""
    Ternary Platform API

    Ternary Platform API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ternary
from ternary.model.model_profile import ModelProfile


class TestModelProfile(unittest.TestCase):
    """ModelProfile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelProfile(self):
        """Test ModelProfile"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ModelProfile()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
