# flake8: noqa

"""
    Ternary Platform API

    Ternary Platform API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from ternary.api_client import ApiClient

# import Configuration
from ternary.configuration import Configuration

# import exceptions
from ternary.exceptions import OpenApiException
from ternary.exceptions import ApiAttributeError
from ternary.exceptions import ApiTypeError
from ternary.exceptions import ApiValueError
from ternary.exceptions import ApiKeyError
from ternary.exceptions import ApiException
